#### GAME SETTINGS ####
DISPLAY_H = 540
DISPLAY_W = 960
GAME_FONT_SIZE = 20

#### MENU SETINGS ####
MENU_CURSOR_W = 50
MENU_CURSOR_H = 50
MENU_FONT_SIZE = 20

#### GAME GRID #####
BOARD_CURSOR_W = DISPLAY_W - (DISPLAY_W/5)/10
BOARD_CURSOR_H = DISPLAY_H/10
BOARD_CURSOR_COLOR = (119,179,0)

#### SIDE BAR ####
BOARD_SIDE_W = DISPLAY_W/5
